develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35731:35729"
  container_name: rw-metadata-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://192.168.99.100:8000
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/rw-metadata/app
mongo:
  image: mongo
  container_name: rw-metadata-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/rw-metadata:/data/db
  restart: always
